version: "3"

services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  portainer:
    image: portainer/portainer-ce:2.21.4
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: always

  wireguard:
    environment:
      - LANG=en
      - WG_HOST=home.tepzilon.com
      - PASSWORD_HASH=$$2a$$12$$StlonOceRFatNJ36OjmyE.T5HM/thnQqejhfjKFaeCVKz4T.XfoUC
    image: ghcr.io/wg-easy/wg-easy
    volumes:
      - etc-wireguard:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  portainer-data:
  etc-wireguard:

# [*]
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
