- name: Manage user
  tags: manage-user
  hosts: exit-node
  become: true
  remote_user: ubuntu
  tasks:
    - name: Add user tepzilon
      ansible.builtin.user:
        name: tepzilon
        comment: "Techid Janphaka"
        shell: /bin/bash
        password: "$6$rounds=656000$exposedsalt$mlL0jIYb86sxXIgXg4p59pMml/ELjN45xQMHDyZEZFwQ51d9updS3KjnV4mWeaaM4Gd7cvICY9vy6PBPbc56h/"
        group: sudo
    - name: Add SSH key to user tepzilon
      ansible.posix.authorized_key:
        user: tepzilon
        state: present
        key: "{{ lookup('file', '../secrets/homestack-exit-node-ssh-key.pub') }}"

- name: Install Docker
  tags: install-docker
  hosts: exit-node
  become: true
  remote_user: tepzilon
  tasks:
    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: latest
        update_cache: true
    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        update_cache: true
    # There is a problem where docker container cannot access internet.
    # The root cause is one of the rule in iptables chain FORWARD rejected packets.
    # Solving this by adding the rule in iptables chain DOCKER-USER to accept all packets from/to Docker network [*]
    - name: Add iptables rule for Docker network (incoming packets)
      ansible.builtin.iptables:
        chain: DOCKER-USER
        source: 172.18.0.0/16
        action: insert
        jump: ACCEPT
    - name: Add iptables rule for Docker network (outgoing packets)
      ansible.builtin.iptables:
        chain: DOCKER-USER
        destination: 172.18.0.0/16
        action: insert
        jump: ACCEPT
    # TODO: find a way to persist iptables rules

- name: Run Docker services
  tags: run-docker-services
  hosts: exit-node
  become: true
  remote_user: tepzilon
  tasks:
    - name: Create a homestack directory
      ansible.builtin.file:
        path: /home/tepzilon/homestack
        state: directory
        owner: tepzilon
        group: sudo
        mode: "0774"
    - name: Copy Docker compose file
      ansible.builtin.copy:
        src: ../services/docker-compose.yaml
        dest: /home/tepzilon/homestack/docker-compose.yaml
        owner: tepzilon
        group: sudo
        mode: "0774"
    - name: Create a NGINX config directory
      ansible.builtin.file:
        path: /home/tepzilon/homestack/nginx/conf
        state: directory
        owner: tepzilon
        group: sudo
        mode: "0774"
    - name: Copy NGINX default http config file
      ansible.builtin.copy:
        src: ../services/nginx-default-http.conf
        dest: /home/tepzilon/homestack/nginx/conf/nginx-default-http.conf
        owner: tepzilon
        group: sudo
        mode: "0774"
    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: /home/tepzilon/homestack
      register: output
    - name: Show services creation and start results
      ansible.builtin.debug:
        var: output

- name: Generate certificate
  hosts: exit-node
  become: true
  remote_user: tepzilon
  tags: generate-certificate
  tasks:
    - name: Remove NGINX default https config file
      ansible.builtin.file:
        path: /home/tepzilon/homestack/nginx/conf/nginx-default-https.conf
        state: absent
    - name: Reload NGINX
      community.docker.docker_compose_v2_exec:
        service: reverse-proxy
        argv:
          - nginx
          - -s
          - reload
        project_src: /home/tepzilon/homestack
    - name: Run certbot
      community.docker.docker_compose_v2_run:
        service: certbot
        argv:
          - certonly
          - --webroot
          - --webroot-path
          - /var/www/certbot/
          - --non-interactive
          - --agree-tos
          - --email
          - techid2000@gmail.com
          - --domains
          - home.tepzilon.com
        project_src: /home/tepzilon/homestack
      register: result
    - name: Print stdout
      ansible.builtin.debug:
        var: result.stdout
    - name: Copy NGINX default https config file
      ansible.builtin.copy:
        src: ../services/nginx-default-https.conf
        dest: /home/tepzilon/homestack/nginx/conf/nginx-default-https.conf
        owner: tepzilon
        group: sudo
        mode: "0774"
    - name: Reload NGINX
      community.docker.docker_compose_v2_exec:
        service: reverse-proxy
        argv:
          - nginx
          - -s
          - reload
        project_src: /home/tepzilon/homestack

- name: Renew certificate
  hosts: exit-node
  become: true
  remote_user: tepzilon
  tags: renew-certificate
  tasks:
    - name: Run certbot renew
      community.docker.docker_compose_v2_run:
        service: certbot
        argv:
          - renew
        project_src: /home/tepzilon/homestack
